### ISSUE TITLE
Implementing vmi_events_listen(0)

### ISSUE THREAD

**Issue by mtarral** [KVM-VMI/libvmi#12] opened 2019-10-01 13:39 UTC
Hi,

I would like to start a discussion about how `vmi_events_listen(vmi, 0)` should be implementing with the APIs available in KVMi.

As we know, the API definition is the following:
https://github.com/libvmi/libvmi/blob/master/libvmi/events.h#L760
> 
>  * Listen for events until one occurs or a timeout.
>  * If the timeout is given as 0, it will process leftover events
>  * in the ring-buffer (if there are any).

The current implementation I gave in [my first PR on v5 events](https://github.com/KVM-VMI/libvmi/pull/9) is not handling the case where `timeout=0`, to **process leftover events**.

## Simple implementation

We could consider the following implementation, with a `do ... while()` loop

~~~C
status_t
kvm_events_listen(
    vmi_instance_t vmi,
    uint32_t timeout)
{
#ifdef ENABLE_SAFETY_CHECKS
    if (!vmi)
        return VMI_FAILURE;
#endif
    struct kvmi_dom_event *event = NULL;
    unsigned int ev_reason = 0;
    // if timeout is 0, we have to process all leftover events on the ring
    bool process_all_events = (timeout == 0) ? true : false;

    kvm_instance_t *kvm = kvm_get_instance(vmi);
#ifdef ENABLE_SAFETY_CHECKS
    if (!kvm || !kvm->kvmi_dom)
        return VMI_FAILURE;
#endif

    do {
        // wait next event
        if (kvmi_wait_event(kvm->kvmi_dom, (kvmi_timeout_t)timeout)) {
            if (errno == ETIMEDOUT) {
                // no events !
                break;
            }
            errprint("%s: kvmi_wait_event failed: %s\n", __func__, strerror(errno));
            return VMI_FAILURE;
        }

        // pop event from queue
        if (kvmi_pop_event(kvm->kvmi_dom, &event)) {
            errprint("%s: kvmi_pop_event failed: %s\n", __func__, strerror(errno));
            return VMI_FAILURE;
        }

        // handle event
        ev_reason = event->event.common.event;
#ifdef ENABLE_SAFETY_CHECKS
        if ( ev_reason >= KVMI_NUM_EVENTS || !kvm->process_event[ev_reason] ) {
            errprint("Undefined handler for %u event reason\n", ev_reason);
            goto error_exit;
        }
#endif
        // call handler
        if (VMI_FAILURE == kvm->process_event[ev_reason](vmi, event))
            goto error_exit;

        if (event) {
            free(event);
            event = NULL;
        }
    } while (process_all_events);

    return VMI_SUCCESS;
error_exit:
    if (event)
        free(event);
    return VMI_FAILURE;
} 
~~~

## Problematic use case

Considering this simple use-case:
~~~C
vmi_pause_vm(vmi);
...
vmi_events_listen(vmi, 0); <--- This call should clean the ring and process leftover events, while keeping the VM paused.
~~~

## Pause events ?

With the API available today in KVMi, it is quite challenging to honor the behavior expected by the user.

The main problem lies in the fact that pausing the VM in KVMi means that a `KVMI_EVENT_PAUSE_VCPU` event will be queued in the event ring.

Therefore our implementation will remove these events from the ring.
From the moment where we remove them, we have to give a reply to the VCPU with the event sequence number.

I'm puzzled by how we can handle this implementation correctly and I would like your advices.

ideas:
- pop the pause events anyway, reply continue and call `vmi_pause_vm` to reque the pause events at the end (if we encountered pause events) ? not doable, the vcpu will be running anyway since we sent a reply.
- pop the next event, if it's a pause events, store it for the next `vmi_resume_vm` call ? :thinking: 

cc @mdontu, @adlazar, @tklengyel, @smaresca

Thanks.

**Comment by tklengyel** [comment] 2019-10-01 13:45
I'm a bit behind the curve here, do you have new event type for KVM that sends a notification to the monitor when the vCPU is getting paused?

**Comment by mtarral** [comment] 2019-10-01 13:49
Yes, that's how [`kvmi_pause_all_vcpus()`](https://github.com/KVM-VMI/libvmi/blob/kvmi/libvmi/driver/kvm/include/kvmi/libkvmi.h#L86) works.

Pausing the VCPU means a `KVMI_EVENT_PAUSE_VCPU` will be queued, per vcpu

To continue the execution you have to pop this event, and [reply `KVMI_EVENT_ACTION_CONTINUE`](https://github.com/KVM-VMI/libvmi/blob/kvmi/libvmi/driver/kvm/kvm.c#L916) with the event's sequence number.

**Comment by adlazar** [comment] 2019-10-01 14:48
When `kvmi_pause_all_vcpus()` returns, you _can be sure_ that no vCPU thread runs guest code. You should get a pause event from all vCPUs, but if you subscribed to other events and one of them happens, you might get that event first (eg. MSR change) and the pause event will be delayed (for that vCPU) until you reply to that MSR event.

You can pop the pause events (and reply later with their sequence numbers), but you can't get more than one event from a vCPU (thread). So, if you don't reply to the pause event from vCPU0, you can't receive another event from vCPU0.

I don't see why do you want to pause the VM and remove leftover events. Usually, you pause the VM (call `kvmi_pause_all_vcpus()` and mark the VM as paused), do some changes that will trigger some introspection events later (eg. protect pages, insert breakpoints), mark the VM as not paused and wait for the expected events. If you pop a pause event while the VM is marked as not paused, you reply with continue (treating these events as leftovers).

**Comment by mtarral** [comment] 2019-10-01 15:03
> I don't see why do you want to pause the VM and remove leftover events.

You mean that this use case doesn't make sense ?
~~~C
vmi_pause_vm(vmi);
vmi_events_listen(vmi, 0);
~~~

Because this is how a libvmi program can make sure that the event ring is cleared, before resuming the VM execution for example.
Personally, this is how I implemented various functions in my programs, for example:
- singlestepping one instruction
- pausing the vm once the instruction has been executed
- clearing the event queue to discard other singlestep events in the queue.
https://github.com/Wenzel/pyvmidbg/blob/master/vmidbg/breakpoint.py#L157

@tklengyel can you confirm that this is a legitimate usage of the library ?
(Also this function will make use `vmi_toggle_single_step_vcpu`, that's why I made the PR...)

**Comment by tklengyel** [comment] 2019-10-01 16:10
Yes, it is the only way you can ensure all events that are queued are fully processed and that the VM is a known state. Otherwise you have a race-condition as the VM can produce a new event if any of its vCPUs are active.

**Comment by tklengyel** [comment] 2019-10-01 20:16
@adlazar 

> I don't see why do you want to pause the VM and remove leftover events. Usually, you pause the VM (call kvmi_pause_all_vcpus() and mark the VM as paused), do some changes that will trigger some introspection events later (eg. protect pages, insert breakpoints), mark the VM as not paused and wait for the expected events. If you pop a pause event while the VM is marked as not paused, you reply with continue (treating these events as leftovers).

In the cases you describe that's correct. But think about what happens when you want to disable events on the fly - say remove a breakpoint. If you just pause the VM and remove the breakpoint and its LibVMI handler, nothing guarantees that there is no breakpoint event already queued that you just haven't processed yet. So after you pause the VM you must do another round to check nothing got produced in the time it took to pause the VM.

**Comment by adlazar** [comment] 2019-10-02 09:43
I see. But you still need to handle _the unexpected_ :) For example, handle breakpoint events not caused by the introspection tool or handle a trap event (this is caused by an exception being injected before or during the pause, and it might be send after the vCPU is resumed if the exception could not be injected).

I'll go with this solution:
> pop the next event, if it's a pause events, store it for the next vmi_resume_vm call ?

`vmi_pause_vm()` already counts how many pause events the introspection tool has to receive. `vmi_resume_vm()` will be the only code *replying* to pause events, while `vmi_events_listen()` will _handle_ the pause events by queuing them for `vmi_resume_vm()`. On resume, the queued pause events are responded to (and listen for more if needed).

To reply to these events, you need only the vCPU index and the sequence number.

**Comment by Wenzel** [comment] 2020-11-30 15:26
Closing this issue as it has been resolved

**Closed as completed by Wenzel** 2020-11-30 15:26 UTC
